

CREATE TABLE OCCUPATION(
    NID NUMBER,
    GENERAL_OC VARCHAR2(15),
    SPECIFIC_OC VARCHAR2(15),
    SALARY NUMBER,
    CONSTRAINTS FK_OCCUPATION_CITIZEN FOREIGN KEY(NID) REFERENCES CITIZEN(NID)
);

INSERT INTO OCCUPATION VALUES(1, 'PROGRAMMER', 'DEV', 1600000);
INSERT INTO OCCUPATION VALUES(2, 'TEACHER', 'SCHOOL', 900000);
INSERT INTO OCCUPATION VALUES(3, 'TEACHER', 'UNIVERSITY', 800000);
INSERT INTO OCCUPATION VALUES(4, 'DOCTOR', 'MEDICINE', 400000);
INSERT INTO OCCUPATION VALUES(5, 'ENGINEER', 'CSE', 400000);
INSERT INTO OCCUPATION VALUES(6, 'PROGRAMMER', 'DEV', 200000);
INSERT INTO OCCUPATION VALUES(7, 'PROGRAMMER', 'DEV', 100000);
INSERT INTO OCCUPATION VALUES(8, 'TEACHER', 'SCHOOL', 100000);
INSERT INTO OCCUPATION VALUES(9, 'ENGINEER', 'EEE', 700000);
INSERT INTO OCCUPATION VALUES(10, 'ENGINEER', 'CSE', 1100000);


-- TASK: A

1. 
SELECT GENERAL_OC, SPECIFIC_OC, COUNT(*) AS TOTAL
FROM OCCUPATION
GROUP BY GENERAL_OC, SPECIFIC_OC
ORDER BY TOTAL DESC;

2. 
SELECT GENERAL_OC, MAX(SALARY), MIN(SALARY), AVG(SALARY)
FROM OCCUPATION 
GROUP BY GENERAL_OC;

3. 
SELECT GENERAL
FROM (SELECT GENERAL_OC AS GENERAL, AVG(SALARY) AS AVG_GENERAL_OC
	  FROM OCCUPATION
	  GROUP BY GENERAL_OC)
WHERE AVG_GENERAL_OC >= (SELECT AVG(SALARY) FROM OCCUPATION);

4. 
CREATE VIEW CUSTOM_VIEW AS
SELECT GENERAL, AVG_GENERAL_OC
FROM (SELECT GENERAL_OC AS GENERAL, AVG(SALARY) AS AVG_GENERAL_OC
	  FROM OCCUPATION
	  GROUP BY GENERAL_OC);
	  
SELECT GENERAL, AVG_GENERAL_OC
FROM CUSTOM_VIEW
WHERE AVG_GENERAL_OC = (SELECT MAX(AVG_GENERAL_OC) FROM CUSTOM_VIEW);


-- Task: B

CREATE TABLE GRADES (
	ID NUMBER,
	DEPARTMENT VARCHAR2(10),
	PROGRAMME VARCHAR2(10),
	COURSE VARCHAR2(10),
	GRADE VARCHAR2(10),
	CONSTRAINTS PK_GRADES PRIMARY KEY(ID),
	CONSTRAINTS CHECK_DEPARTMENT CHECK (DEPARTMENT IN ('CSE', 'EEE')),
	CONSTRAINTS CHECK_PROGRAMME CHECK (PROGRAMME IN ('BSc', 'HD')),
	CONSTRAINTS CHECK_GRADE CHECK (GRADE IN ('A+', 'A', 'A-'))
);

INSERT INTO GRADES VALUES(1, 'CSE', 'BSc', 'CSE4508', 'A+');
INSERT INTO GRADES VALUES(2, 'EEE', 'BSc', 'EEE4509', 'A+');
INSERT INTO GRADES VALUES(3, 'CSE', 'HD', 'CSE4510', 'A');
INSERT INTO GRADES VALUES(4, 'EEE', 'HD', 'EEE4511', 'A-');
INSERT INTO GRADES VALUES(5, 'CSE', 'BSc', 'CSE4512', 'A-');


1.
SELECT DEPARTMENT, PROGRAMME, COURSE, GRADE, COUNT(*) AS TOTAL
FROM GRADES
GROUP BY ROLLUP(DEPARTMENT, PROGRAMME, COURSE, GRADE)
ORDER BY DEPARTMENT, PROGRAMME;

2.
SELECT DEPARTMENT, PROGRAMME, COURSE, GRADE, COUNT(*) AS TOTAL
FROM GRADES
GROUP BY CUBE(DEPARTMENT, PROGRAMME, COURSE, GRADE)
ORDER BY DEPARTMENT, PROGRAMME;
